### ISSUE TITLE
Convert Multi-select fields to Checkbox selections

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#222]
## User Story

As a translation manager I would like the ability to check boxes in fields where more than one answer applies because cntrl-clicking is not intuitive

## Definition of Done
Research to see if this can be done in Django

**Comment by markalolo** [comment]
https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#built-in-widgets

Typed with two thumbs and sent from my iPhone

On Oct 7, 2015, at 10:13 AM, Glenn Oliver <notifications@github.com<mailto:notifications@github.com>> wrote:

User Story

As a translation manager I would like the ability to check boxes in fields where more than one answer applies because cntrl-clicking is not intuitive

Definition of Done

Research to see if this can be done in Django

-

**Comment by Redmayspecial** [comment]
Near the Top

**Comment by vleong2332** [comment]
Changed the following fields to use multicheckbox:
- publication
- ouput_target
- hardware
- software
- translation_methods
- departments
