### ISSUE TITLE
Allow users to add choices to Event field lists

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#226]
## User Story
As a translation manager I want the ability to create an new entry in certain fields in order to accurately reflect that event detail that transpired.

## Definition of Done
Create a mechanism from the Event form to allow users to modify the list contents for specific fields.

## Checklist
- [ ] Networks
- [ ] Translation Methodologies  (Seek Tim's counsel)
- [ ] Software/App Used
- [ ] Hardware Used
- [ ] Output Target
- [ ] Publishing Medium

**Comment by Redmayspecial** [comment]
Translation Methodologies (Seek Tim's counsel)

**Comment by Redmayspecial** [comment]
TOP Priority

**Comment by vleong2332** [comment]
## Concerns:
- User may want to enter unexpected input (a.k.a item that's not on the list)
- User many not want to submit a help request to add item to the list because of time or connectivity constrains.
- User may want to complete paper(form)-work in one sitting because of the same constrains.
- Support person with the right privilege level may not be readily available when needed.
- Data integrity must be maintained because what's put in here will be displayed back to the user and other users.

## Proposed Solutions:
- Let user puts in additional information to the list <== Threatens data integrity
- Ask user to submit help request to put additional information in the list <== Highly inconvenient in some circumstances
- Give option for 'others' and then give user a separate (super-simple) form to specify what 'others' are. This...
   - alerts the program and/or support person that additional info needs to be reviewed and then put in.
   - provides an opportunity to maintain data integrity either manually or through code.
   - lets the above two points to be done on a separate time table while not making the user wait for an answer.
   - lets user completes paper(form)-work in one sitting even if his desired response is not contained in the choices we provide.
   - avoids adding additional complexity to the current form (already too long).
   - makes my life easier (I strongly hope).
