### ISSUE TITLE
Publish Event Notifications

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#284]
We need to devise a system whereby users can sign up to receive publication notices.  For now, let's make it simple so that someone can sign up to receive all publish events.  Later we could add options for selecting individual resources or languages.

Intended behavior is that these people will be sent an email that notifies them of the newly published content.  Something to the effect of:
```
Subject: OBS Published in sgj
Body:  Hello,
The resource OBS has recently been published for the sgj language.  The version is {ver} and the checking the level is {lev}.

Sincerely,
Your Publishing Bot
```

**Comment by russp41** [comment]
Hi Jesse,
Thanks for opening this issue. Would it be possible to also generate an email for a couple of other points in the process? 

A key one would be when a publishing request is first submitted for the resource. We encourage translation teams to submit publishing requests, but we don't know when they actually submit it unless they think to notify us.

Another alert could be when a publishing request is flagged as incomplete, rejected, or otherwise some exception happens.

Thanks,

Russ Perry
