### ISSUE TITLE
Remove the "Countries where language is spoken" from the charter form

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#402]
Check with Paul Foxworthy 

- [ ] Is there data behind this in TD?
- [ ] Is there existing data on this from other sources to make this collection redundant?

**Comment by vleong2332** [comment]
@Redmayspecial 
> Is there data behind this in TD?
There is an existing data in tD pulled in by @paltman of in what countries a language is spoken. I think the concern here is "how can ops people add new info as they discover it?" or "should they be able to add new info?"

Regardless of the answer, the field should be removed from the charter form because it's not the right place to put it. Two options that I see:
1. It should be put in Add/Edit Language when the form is available for user. Right now it's blocked by #403 and #248 
2. A separate form dedicated to update this info **only** for existing language.
