### ISSUE TITLE
Commenting System

### ISSUE THREAD

**Issue by markalolo** [unfoldingWord-dev/translationDatabaseWeb#515]
# User Story

As an Ops Team Member, I want to log comments about languages as I discover new information, so that everyone who's logged in can see what we have learned about a given language based on field information.

Maybe this will help:

https://www.djangopackages.com/packages/p/django-comments-xtd/

**Comment by vleong2332** [comment]
- [ ] Add the field in all language form.
- [ ] Ensure that the comment can be seen in language detail page.

**Comment by markalolo** [comment]
I think our users need to be able to log comments all over the site, including countries, project charters, events, regions, etc. We also need to think about being able to tag other pieces of data using Hashtags. The idea being that you can make a comment in one place that #Hashtags other things (maybe another language, or a workshop, or something), and then that comment would appear on that data as well. This is a rapidly rising priority as the team needs to start cataloging what they are learning on the ground.

**Comment by markalolo** [comment]
Also, here's a grid of some commenting packages: [https://www.djangopackages.com/grids/g/commenting/](url)

**Comment by vleong2332** [comment]
_Mark's Email:_

Here’s my bad mockups for tD discussion tomorrow! The tricky ones will be the pivot tables. Because I love you all, here’s some more input: https://github.com/pgollakota/django-chartit :)

On the commenting system, I’m thinking about being able to add comments. Comments would be time-stamped and user-stamped. The fun part would be implementing the ability to use hashtags to link the comment to multiple pieces of data. The data I’m thinking about would include:

#country
#region
#language
#project
#event

So when the data was posted into the database, we’d check for hashtags and store those separately, along with the page the comment originated on. Then if you looked at any of the other pages that were hashtagged you’d see the comment there, like this:

Let’s say I’m on a language page like Eastern Bru (http://td.unfoldingword.org/uw/languages/917/). And I enter a comment like:

“This is a dialect of #tdf also spoken in #Laos.”

That comment would show up on Eastern Bru.

And on the Laos Page, you would see a list of comments, including this one that said something like:

“Eastern Bru: This is a dialect of #tdf also spoken in #Laos. – Mark Stedman 4/28/16”

And on the Taileng page it would say something like:

“Eastern Bru (put the actual name here? Hyperlinked?): This is a dialect of Taileng also spoken in #Laos. – Mark Stedman 4/28/16”

Make sense?

Mark

**Comment by vleong2332** [comment]
[tD additional screens.docx](https://github.com/unfoldingWord-dev/translationDatabaseWeb/files/242575/tD.additional.screens.docx)

**Comment by vleong2332** [comment]
# Requirements
- Comment should be time-stamped
- Comment should be user-stamped
- Comment should allow hashtag to link to other pieces of data (country, region, language, project, event)
- Hashtagged objects should display the original comment in it's detail page
