### ISSUE TITLE
Add Alternate Language Names to langnames.json

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#56]
We need to add all of the known alternate language names to the langnames.json export.
First priority:

* [x] Include English names for all languages (we already have this info in http://td.unfoldingword.org/data-sources/wikipedia/).  We also have the description field from http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry that has the English name of the language.

Secondary priority:
* [x] See if we can find and import other "alternate" names for languages.  Possibly scraping ethnologue.

**Comment by swilcox** [comment]
I know we have the "common" (aka English) names in some of our import databases but obviously, there might be multiple (hence your use of the word "all"). Do you have a source in mind for that or do you think pulling the "common" name in plus having some maintenance views/forms would be adequate? And would we need then provide the alternate language names in the form of a list ["name1", "name2"] in the json? Is that what you were thinking?

**Comment by jag3773** [comment]
Yes, this information should be available from the Ethnologue import.  And yes, a list in the JSON is necessary.

**Comment by smcoll** [comment]
@jag3773 can you point me to an example of an alternate language name in the Ethnologue data?  i only see a single name for each code in these sources:
 - http://www.ethnologue.com/sites/default/files/LanguageIndex.tab  
 - http://www.ethnologue.com/sites/default/files/LanguageCodes.tab

Are the alternate language names simply additional English names for the same language, or are we talking about adding multilingual support for language names?

**Comment by jag3773** [comment]
Just to clarify... two issues here:

* [ ] Include English names for all languages (we already have this info in http://td.unfoldingword.org/data-sources/wikipedia/).
* [ ] See if we can find and import other "alternate" names for languages.

**Comment by cdaield** [comment]
ISO 639 2t, 2b, and 3 are all listed as 'eng' for English, so if we are just providing a list, it would just be `['en','eng','engs']` - or do we want a dictionary to allow preserving of which ISO format is being represented?

**Comment by paltman** [comment]
I think we just need to modify https://github.com/unfoldingWord-dev/translationDatabaseWeb/blob/master/td/tasks.py#L25 to pull in the english name from the wikipedia source and add an attribute to the Language model rather than adding it as another EAV.

**Comment by paltman** [comment]
Alternative names hasn't been done yet. We need to identify a source to load.

**Comment by jag3773** [comment]
Issue #304 may be related.

**Comment by vleong2332** [comment]
Here's a source: http://joshuaproject.net/assets/media/data/jpharvfielddataonly.zip
It's MS Access file. In there, there's a table called something like `LangAltNames`.

The table can be exported to a `.csv` from MS Access. We can definitely do a one-time import of the data and put it in a `LanguageAltName` model. Then give `Language` a property to return the string of alternate names - like `Language.cc_all`. At least this is how I think I can work it out. Of course this would be a problem for searching since property is not a database field.

What do you think, @paltman? Can we extract the table by code and integrate the data (most likely an array of strings) into `Language` as a field?

**Comment by paltman** [comment]
Why not just add the alternate names to the Langauge table as multiple EAV values. We are already using EAVs for this (country for example)?

**Comment by vleong2332** [comment]
I saw that, but wasn't sure what it was for and how it works. That could be a better idea. I'll research that. Any pointer on where to look, @paltman?

**Comment by vleong2332** [comment]
@paltman I registered `LanguageEAV` to admin and I think I know how they relate. I just can't figure out how the `LanguageEAV` is populated. A search through the project only revealed 3 uses for that model 1) in migration when it's created, 2) in the `models.py` when it's declared, and 3) in the admin when it's registered.

Is the the model populated implicitly somewhere?

**Comment by vleong2332** [comment]
@paltman @Redmayspecial @jag3773 I currently have it working in my dev and it looks like this
```
{
    "gw":false,
    "ld":"ltr",
    "ang":"Afar",
    "lc":"aa",
    "cc":["DJ","ET","ER","US","CA"],
    "ln":"Afaraf",
    "lr":"Africa",
    "pk":6,
    "alt": [
        "Afaraf",
        "Danakil",
        "Afaraf",
        "Danakil",
        "Denkel",
        "Adal",
        ...
        "Baadu (Ba'adu)"
    ]
}
````

The size of the JSON went up to ~1.38 MB from ~912 KB (measured by saving the JSON as a file then looking at the properties).

Note that the data that's used to import may be cleaned up a bit as I see possible duplication so that may cause the size delta to decrease slightly.

Any thoughts?

**Comment by jag3773** [comment]
Size increase is not a problem in this case, we need the data.  There is some duplication in that snippet you posted, so maybe we can filter out duplicate entries between `ang`, `ln`, and `alt` ?
